{"uid":"8edf7ef239f13343","name":"test_password_is_login[standard_user-locked_out_user]","fullName":"tests.test_login_page#test_password_is_login","historyId":"8cf6cc5192c93d8563b9b7e0004a55da","time":{"start":1669526180983,"stop":1669526180983,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5556353e0463 <unknown>\n#1 0x5556351a48d8 <unknown>\n#2 0x5556351ccb6a <unknown>\n#3 0x5556351c7c05 <unknown>\n#4 0x55563520b802 <unknown>\n#5 0x55563520b2af <unknown>\n#6 0x555635203443 <unknown>\n#7 0x5556351d43c5 <unknown>\n#8 0x5556351d5531 <unknown>\n#9 0x555635432dce <unknown>\n#10 0x555635436192 <unknown>\n#11 0x55563541793e <unknown>\n#12 0x555635437103 <unknown>\n#13 0x55563540ad85 <unknown>\n#14 0x5556354580a8 <unknown>\n#15 0x555635458239 <unknown>\n#16 0x555635473492 <unknown>\n#17 0x7f485c678609 start_thread","statusTrace":"username = 'standard_user', password = 'locked_out_user'\n\n    @pytest.fixture(scope=\"function\")\n    def browser(username, password):\n        options = webdriver.ChromeOptions()\n        options.add_argument(\"--window-size=1600,1080\")\n        options.headless = False\n>       browser = webdriver.Chrome(\n            service=ChromeService(ChromeDriverManager().install()), options=options\n        )\n\nconftest.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:81: in __init__\n    super().__init__(\n../../../.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:106: in __init__\n    super().__init__(\n../../../.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:288: in __init__\n    self.start_session(capabilities, browser_profile)\n../../../.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:381: in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n../../../.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:444: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f185b679f60>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: Chrome failed to start: exited a...wn>\\\\n#15 0x555635458239 \\\\u003Cunknown>\\\\n#16 0x555635473492 \\\\u003Cunknown>\\\\n#17 0x7f485c678609 start_thread\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        Checks that a JSON response from the WebDriver does not have an error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value.keys()) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        if status in ErrorCode.NO_SUCH_ELEMENT:\n            exception_class = NoSuchElementException\n        elif status in ErrorCode.NO_SUCH_FRAME:\n            exception_class = NoSuchFrameException\n        elif status in ErrorCode.NO_SUCH_SHADOW_ROOT:\n            exception_class = NoSuchShadowRootException\n        elif status in ErrorCode.NO_SUCH_WINDOW:\n            exception_class = NoSuchWindowException\n        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:\n            exception_class = StaleElementReferenceException\n        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:\n            exception_class = ElementNotVisibleException\n        elif status in ErrorCode.INVALID_ELEMENT_STATE:\n            exception_class = InvalidElementStateException\n        elif (\n            status in ErrorCode.INVALID_SELECTOR\n            or status in ErrorCode.INVALID_XPATH_SELECTOR\n            or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER\n        ):\n            exception_class = InvalidSelectorException\n        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:\n            exception_class = ElementNotSelectableException\n        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:\n            exception_class = ElementNotInteractableException\n        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:\n            exception_class = InvalidCookieDomainException\n        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:\n            exception_class = UnableToSetCookieException\n        elif status in ErrorCode.TIMEOUT:\n            exception_class = TimeoutException\n        elif status in ErrorCode.SCRIPT_TIMEOUT:\n            exception_class = TimeoutException\n        elif status in ErrorCode.UNKNOWN_ERROR:\n            exception_class = WebDriverException\n        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:\n            exception_class = UnexpectedAlertPresentException\n        elif status in ErrorCode.NO_ALERT_OPEN:\n            exception_class = NoAlertPresentException\n        elif status in ErrorCode.IME_NOT_AVAILABLE:\n            exception_class = ImeNotAvailableException\n        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:\n            exception_class = ImeActivationFailedException\n        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:\n            exception_class = MoveTargetOutOfBoundsException\n        elif status in ErrorCode.JAVASCRIPT_ERROR:\n            exception_class = JavascriptException\n        elif status in ErrorCode.SESSION_NOT_CREATED:\n            exception_class = SessionNotCreatedException\n        elif status in ErrorCode.INVALID_ARGUMENT:\n            exception_class = InvalidArgumentException\n        elif status in ErrorCode.NO_SUCH_COOKIE:\n            exception_class = NoSuchCookieException\n        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:\n            exception_class = ScreenshotException\n        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:\n            exception_class = ElementClickInterceptedException\n        elif status in ErrorCode.INSECURE_CERTIFICATE:\n            exception_class = InsecureCertificateException\n        elif status in ErrorCode.INVALID_COORDINATES:\n            exception_class = InvalidCoordinatesException\n        elif status in ErrorCode.INVALID_SESSION_ID:\n            exception_class = InvalidSessionIdException\n        elif status in ErrorCode.UNKNOWN_METHOD:\n            exception_class = UnknownMethodException\n        else:\n            exception_class = WebDriverException\n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = \"{}.{}\".format(frame[\"className\"], meth)\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\nE         (unknown error: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x5556353e0463 <unknown>\nE       #1 0x5556351a48d8 <unknown>\nE       #2 0x5556351ccb6a <unknown>\nE       #3 0x5556351c7c05 <unknown>\nE       #4 0x55563520b802 <unknown>\nE       #5 0x55563520b2af <unknown>\nE       #6 0x555635203443 <unknown>\nE       #7 0x5556351d43c5 <unknown>\nE       #8 0x5556351d5531 <unknown>\nE       #9 0x555635432dce <unknown>\nE       #10 0x555635436192 <unknown>\nE       #11 0x55563541793e <unknown>\nE       #12 0x555635437103 <unknown>\nE       #13 0x55563540ad85 <unknown>\nE       #14 0x5556354580a8 <unknown>\nE       #15 0x555635458239 <unknown>\nE       #16 0x555635473492 <unknown>\nE       #17 0x7f485c678609 start_thread\n\n../../../.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:249: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser","time":{"start":1669526180984,"stop":1669526181707,"duration":723},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5556353e0463 <unknown>\n#1 0x5556351a48d8 <unknown>\n#2 0x5556351ccb6a <unknown>\n#3 0x5556351c7c05 <unknown>\n#4 0x55563520b802 <unknown>\n#5 0x55563520b2af <unknown>\n#6 0x555635203443 <unknown>\n#7 0x5556351d43c5 <unknown>\n#8 0x5556351d5531 <unknown>\n#9 0x555635432dce <unknown>\n#10 0x555635436192 <unknown>\n#11 0x55563541793e <unknown>\n#12 0x555635437103 <unknown>\n#13 0x55563540ad85 <unknown>\n#14 0x5556354580a8 <unknown>\n#15 0x555635458239 <unknown>\n#16 0x555635473492 <unknown>\n#17 0x7f485c678609 start_thread\n\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/Sauce/Sauce/conftest.py\", line 29, in browser\n    browser = webdriver.Chrome(\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 81, in __init__\n    super().__init__(\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 106, in __init__\n    super().__init__(\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-NlGQ8SHG-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"password","time":{"start":1669526192748,"stop":1669526192748,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"username","time":{"start":1669526198221,"stop":1669526198221,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[],"labels":[{"name":"story","value":"TC_001.00.04 | Login page > Авторизация при вводе в поле 'Password' валидного логина"},{"name":"feature","value":"US_001.00 | Login page > Страница авторизации."},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login_page"},{"name":"host","value":"fv-az318-892"},{"name":"thread","value":"2714-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"password","value":"'locked_out_user'"},{"name":"username","value":"'standard_user'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"8edf7ef239f13343.json","parameterValues":["'locked_out_user'","'standard_user'"]}